@base_url=http://localhost:3000


GET {{base_url}}/health/ping


### post link endpoint
POST {{base_url}}/links
Content-Type: application/json

{
    "original": "http=://escola.formacao"
}

### redirect link endpoint
GET {{base_url}}/javvl5x

### get all links endpoint
GET {{base_url}}/links/all